language: java
jdk: oraclejdk8

sudo: required

services:
- docker



addons:
  sonarcloud:
    organization: "fabiosoaza-github" 
    token:
      secure: $SONAR_TOKEN

notifications:
  slack:
    on_success: change
    on_failure: always

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

install: true    

before_script:
    - curl https://cli-assets.heroku.com/install-standalone.sh | sh

script:
    - ./pipeline.sh install
    
after_success:
   - ./pipeline.sh after_success   
     
