language: java
jdk: oraclejdk8

notifications:
  slack:
    on_success: change
    on_failure: always

cache:
  directories:
    - $HOME/.m2

install: true    

script:
    - git fetch --prune
    - ./set-versions.sh set_release_version
    - mvn install -B -V    

after_success:
   - bash <(curl -s https://codecov.io/bash)      
   - mvn clean test jacoco:report
   - ./set-versions.sh release
   - mvn deploy --settings maven_settings.xml
   - ./set-versions.sh start 
   - ./set-versions.sh push       


