language: java
jdk: oraclejdk8

sudo: required

services:
- docker

addons:
  sonarcloud:
    organization: "fabiosoaza-github" 
    token:
      secure: $SONAR_TOKEN

notifications:
  slack:
    on_success: change
    on_failure: always

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

install: true    

script:
    - ./pipeline.sh install
    
after_success:
   - ./pipeline.sh after_success   
      
deploy:
  provider: heroku
  api_key: $HEROKU_TOKEN
  app: spring-rest-base
  on: 
    all_branches: true

