language: java
jdk: oraclejdk8

notifications:
  slack:
    on_success: change
    on_failure: always

cache:
  directories:
    - $HOME/.m2

after_success:
   - bash <(curl -s https://codecov.io/bash)      
   - mvn clean test jacoco:report
