language: java
jdk: oraclejdk8

notifications:
  slack:
    on_success: change
    on_failure: always

cache:
  directories:
    - $HOME/.m2

install: true    

script:
    - ./set-versions.sh install
    
after_success:
   - ./set-versions.sh after_success   
      


