FROM gustajz/liquibase


ENV LIQUIBASE_DIR=/liquibase
ENV CHANGELOG_DIR=$LIQUIBASE_DIR/changelogs/
ENV CONFIGS_DIR=$LIQUIBASE_DIR/conf/
ENV LIQUIBASE_PROPERTIES=$CONFIGS_DIR/liquibase.properties
ENV LIQUIBASE_DEFAULTS_FILE=./conf/liquibase.properties    

WORKDIR $LIQUIBASE_DIR

RUN mkdir -p $CHANGELOG_DIR
RUN mkdir -p $CONFIGS_DIR

COPY database-changelogs/db.changelog* $CHANGELOG_DIR
COPY database-changelogs/*properties $CONFIGS_DIR

RUN sed -i 's/localhost:5432/db:5432/' $LIQUIBASE_PROPERTIES


CMD sleep 20 && ./liquibase --defaultsFile=$LIQUIBASE_DEFAULTS_FILE update




