version: '3'

services:
      app:
            image: "fabiosoaza/spring-rest-base-app:latest"
            depends_on:
                  - db                 
                  - liquibase 
            ports: 
                  - '8080:8080'
            environment: 
                  - DB_HOST=db
                  - DB_NAME=test
                  - DB_PORT=5432
                  - DB_USER=test
                  - DB_PASS=test
                  - SSL_MODE=disable
                  - MANAGEMENT_USER=test
                  - MANAGEMENT_PASS=test

      db:      
            image: "fabiosoaza/spring-rest-base-database" 
            ports: 
                  - '5432:5432'               
            
      liquibase:
            image: "fabiosoaza/spring-rest-base-liquibase" 
            command: /bin/sh -c "sleep 5 && ./run-liquibase update"
            depends_on:
                  - db
            environment: 
                  - DB_HOST=db
                  - DB_NAME=test
                  - DB_PORT=5432
                  - DB_USER=test
                  - DB_PASS=test
                  - SSL_MODE=disable
            volumes: 
                  - ./database-changelogs/:/liquibase/changelogs/

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 10.20.0.1/16

