version: '2'

services:

      db:      
            image: "fabiosoaza/spring-rest-base-database" 
            ports: 
                  - '5432:5432'               
            
      liquibase:
            image: "fabiosoaza/spring-rest-base-liquibase" 
            depends_on:
                  - db

      app:
            image: "fabiosoaza/spring-rest-base-app" 
            depends_on:
                  - db
                  - liquibase
            ports: 
                  - '8080:8080'
            environment: 
                  - DB_HOST=db
                  - DB_NAME=test
                  - DB_PORT=5432
                  - DB_USER=test
                  - DB_PASS=test

